### ISSUE TITLE
Ducks with selectors

### ISSUE THREAD

**Issue by sapegin** [erikras/ducks-modular-redux#15]
Hi, really like this idea!

Do you have any examples of using [Reselect](https://github.com/rackt/reselect) with Ducks?

**Comment by erikras** [comment]
I have not used reselect, so perhaps someone else can answer.

**Comment by epeli** [comment]
I started to think about this too when Dan commented on the Javascript Air podcast that selectors<sup>1</sup> should be defined next to the reducers because they directly depend on the state shape reducers create. When you refactor reducers you will most often have to refactor the selectors too. And I agree it just makes sense.

<sup>1</sup> Note that this is nothing specific to the Reselect library. Every map state function passed to the react-redux `connect()` is a selector.

But I'm unable to find good convention which would fit into the "ducks spec". One option would be to export `selectors` object but it would be awkward on the consumer side since ES6 imports cannot do nested destructuring like 

```
import {selectors: {getComment}} from "a-duck"
```

Another option would be just to use naming convention, which I'm currently using but not very happy with, like "every exported function which begins with `select` is a state selector."

Example

```js
export function selectComments(postId) {
  // ...
}
```

But it is imo too easy to confuse with action creators.


Any ideas?

**Comment by erikras** [comment]
I use standard "getter" terminology (I come from a Java background) of `getWhatever()` or `isWhatever()` for my selector functions on my ducks. Action creators are verbs other than "get".

**Comment by epeli** [comment]
I agree that `get` is better than `select`. Action Creators rarely "get" anything they fetch, set increase etc. things. But it doesn't remove the fundamental issue.

**Comment by ArnaudRinquin** [comment]
I use `selectors` all the time and put them in my ducks.

It really makes sense as the `selectors` and `reducer` are 100% coupled around the data structure.

Also, I think unit testing reducers and action creators etc... not to be valuable, but testing a duck by only using the action creators and selectors gives you the guarantee that the whole duck works as intended.

Another thing I do regarding selectors: as I want to keep my ducks independent of their position in the app state, I want my selectors to be agnostic as well. In order to do that, on every level of the tree I create a selectors that my ducks import and use as a root selectors:

```
ducks
├── foo.js
├── index.js
├── rootSelector.js
├── users.js
└── widgets
    ├── bar.js
    ├── index.js
    ├── items.js
    └── rootSelector.js

```

Then my ducks look like:

```
import rootSelector from './rootSelector'
import { createSelector } from 'reselect'

export fooSelectors = createSelector(
  rootSelector,
  ({foo}) => foo
)

export fooItemsSelector = createSelector(
  fooSelectors,
  ({items}) => items
)

// ...
```

**Comment by pluma** [comment]
@gaearon's egghead.io series uses `getFoo` (or even `getIsFoo` for booleans) for selectors, so that seems like an endorsement for having a `get` prefix instead of a `Selector` suffix. Also, they're functions (whereas `fooSelector` sounds like it's an object) and having a prefix has the nice benefit of grouping them separately from action creators.

**Comment by sapegin** [comment]
Looks like I found solution that works for me:

```js
import { combineReducers } from 'redux';
import { createStructuredSelector } from 'reselect';

// Actions, reducers, etc.

// Selectors

const isFetching = state => state.isFetching;
const cookies = state => state.data.cookies;

export const selector = createStructuredSelector({
  isFetching,
  cookies,
});
```

And then I connect everything to a component like this:

```js
import * as duck from '../duck';
// ...

@connect(state => duck.selector(state.featureName), dispatch => ({
    actions: bindActionCreators(duck, dispatch),
}))
export default class FeatureNameView extends Component {
  /*_*/
}
```

Check section “Ducks and selectors” in my [article on structuring React apps](http://blog.sapegin.me/all/react-structure) for more details.

**Comment by epeli** [comment]
Another alternative is to export HOCs which will do the selection to component props directly:

```js
import {connect} from "react-redux";

export function addDuckProps(options) {
  return connect(state => ({barProp: state.foo.bar}));
}
```

Usage 

```js
@addDuckProps()
class MyComponent extends Component {
  render() {
    // this.props.barProp is available here
  }
}
```

Of course the downside in this is that you will hardcode the prop names. But then again you can rename those with another HOC if your props collide. For example [`renameProps` from recompose](https://github.com/acdlite/recompose/blob/master/docs/API.md#renameprops).
